services:
  notesme:
    image: ghcr.io/stban1983/notesme:latest
    container_name: notesme
    restart: unless-stopped
    ports:
      - "6807:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
