name: Build and Push multi-arch Docker Image

on:
  workflow_dispatch:  
  push:
    #    branches:
    #      - main
    tags:
      - 'v*.*.*' # Se déclenche aussi quand tu crées un tag Git (ex: v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Configurer QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- NOUVELLE ÉTAPE : Gestion automatique des tags ---
      - name: Extraire les métadonnées (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/stban1983/notesme
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Construire et Pousser l'image (AMD64 & ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          # On utilise les tags générés par l'étape précédente
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
